# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=jormungandr
    - ADDRESS_PREFIX=ceo

matrix:
  include:
    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=arm-unknown-linux-gnueabi DISABLE_TESTS=1
    - env: TARGET=armv7-unknown-linux-gnueabihf DISABLE_TESTS=1
    - env: TARGET=mips64-unknown-linux-gnuabi64 DISABLE_TESTS=1
    - env: TARGET=mips64el-unknown-linux-gnuabi64 DISABLE_TESTS=1
    - env: TARGET=powerpc64-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=powerpc64le-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

    # for building the documentation we disable all the `cross'
    # specific build
    - name: "Documentation"
      env: DOCUMENTATION=1
      os: linux
      language: rust
      rust: stable
      before_install:
      install:
        - which mdbook || cargo install mdbook
        - which mdbook || cargo install mdbook-linkcheck
      script:
        - mdbook build
      after_script:
      before_deploy:

before_install:
  - set -e
  - rustup self update

install:
  - rustup update stable
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  - provider: releases
    api_key:
      secure: mNRWeTyQE6Op+BWvqq7Jg2FD1ZKS59FeuKxKBDtTS7i5edkukqfbjIAsNqojCnnbVeEtBm97oATuW5DQgKkchTiNJBF381F/Z36TjDLi9YztgRRyaBvwOHglqeFt+zzuxKGXmvREE/ar3Rx0xP1mVXfIVC4Dbom91YAl86hyitKbfmA51bFE8GZlH0Ieugn1FpBadntyxb3aqtoJJv8WGPYR9AQouRdWUyNGrhQ6cGYtLU0dOsg6q1C9iD18eFb0yUu4vpuq/sey3eJmfWBSHuLXT9POdCZzwqyj71JdLFDQ/b359AmalIQmgtwIUuX7aRj8Ala6XeprPZZicig1o8es6S4aZNLDs1sRa3BlwHoaUdeqI2xwb9BmSJpRyw6seqeZnD+/eZASwgB8laDuiYmNtHAdmhgxkrk066PWkFUGJ2fxXA6gAn1by5DjU2m7jbX8zSueo33VjTBbQtY2+l/QpRMvMFb7srApf3uHSuPQPFEF13gTj42hTkLVbgroQR0lAYYk+0qR5rF6blZKcFK1ATNA2bmp9Vekb3gqAD7jKV64UIzEIwq2J1bG7FecvG+I+IbnmKuXlruvKq+znB45WG/dav04MOto0Egyq5sIS23u8nS4MgDCeLR/DtYNHQfVH7MbBxc0zoXai+O9QYhuw2u3h2C13/Hi/hcW4jY=
    file_glob: true
    file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
    on:
      condition: $TRAVIS_RUST_VERSION = stable
      tags: true
    skip_cleanup: true

  - provider: pages
    github_token:
      secure: mNRWeTyQE6Op+BWvqq7Jg2FD1ZKS59FeuKxKBDtTS7i5edkukqfbjIAsNqojCnnbVeEtBm97oATuW5DQgKkchTiNJBF381F/Z36TjDLi9YztgRRyaBvwOHglqeFt+zzuxKGXmvREE/ar3Rx0xP1mVXfIVC4Dbom91YAl86hyitKbfmA51bFE8GZlH0Ieugn1FpBadntyxb3aqtoJJv8WGPYR9AQouRdWUyNGrhQ6cGYtLU0dOsg6q1C9iD18eFb0yUu4vpuq/sey3eJmfWBSHuLXT9POdCZzwqyj71JdLFDQ/b359AmalIQmgtwIUuX7aRj8Ala6XeprPZZicig1o8es6S4aZNLDs1sRa3BlwHoaUdeqI2xwb9BmSJpRyw6seqeZnD+/eZASwgB8laDuiYmNtHAdmhgxkrk066PWkFUGJ2fxXA6gAn1by5DjU2m7jbX8zSueo33VjTBbQtY2+l/QpRMvMFb7srApf3uHSuPQPFEF13gTj42hTkLVbgroQR0lAYYk+0qR5rF6blZKcFK1ATNA2bmp9Vekb3gqAD7jKV64UIzEIwq2J1bG7FecvG+I+IbnmKuXlruvKq+znB45WG/dav04MOto0Egyq5sIS23u8nS4MgDCeLR/DtYNHQfVH7MbBxc0zoXai+O9QYhuw2u3h2C13/Hi/hcW4jY=
    file_glob: true
    skip-cleanup: true
    local-dir: book/html
    keep-history: false
    on:
      condition: $DOCUMENTATION = 1

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
